#
#  Configuration for NPCManager plugin.
#

# Show debug messages in console
show-debug-messages: true

# The range at which NPCs will start looking towards the player
npc-headrotation-range: 6

# Reset head rotation when further than the range set in the above field.
reset-headrotation: true

# When creating an NPC, use the name of the NPC to get skin data.
fetch-default-skins: true

# If true, NPC's will perform the punch animation for perfect NPC orientation.
perfect-npc-orientation: true

# The length of an NPC's name to be used in the tablist.
# NPC Tab List names need to be randomised as it fixes a bug
# caused when an online player has the same name as an NPC.
# This needs to be set between 3 and 16.
npc-name-length: 16

# The save method to use.
# Suitable Values:
# JSON (default) - Saves each NPC to its own .json file.
# MYSQL - Saves NPC's to a MYSQL database.
save-method: JSON

# Database Settings. Only applies if using a MYSQL database for storage.
sql:
  host: localhost
  port: 3306
  database: database
  username: root
  password: ""
  useSSL: false
  table-name: npcdata
  