#
#  Configuration for NPCManager plugin.
#

# Show debug messages in console
show-debug-messages: true

# The range at which NPCs will start looking towards the player
npc-headrotation-range: 6

# Reset head rotation when further than the range set in the above field.
reset-headrotation: true

# When creating an NPC, use the name of the NPC to get skin data.
fetch-default-skins: true

# If true, NPC's will perform the punch animation for perfect NPC orientation.
perfect-npc-orientation: true

# How long in ticks to wait before removing an NPC from the tablist.
# It is recommended to keep this at the default setting.
# Setting this too low will cause skins to sometimes not be rendered.
npc-remove-delay: 60

# The length of an NPC's name to be used in the tablist.
# NPC Tab List names need to be randomised as it fixes a bug
# caused when an online player has the same name as an NPC.
# This needs to be set between 3 and 16.
npc-name-length: 16

# The save method to use.
# Suitable Values:
# Remote Databases
#   - MySQL
#   - MongoDB
# Readable and editable text files
#   - JSON
#   - TOML
save-method: JSON

# Database Settings. Only applies if using a remote storage type such as MySQL or MongoDB
data:
  
  # Define the address and port for the database.
  # - Standard DB engine port is used by default.
  #   (MySQL: 3306, MongoDB: 27017)
  # - Specify as "host:port" if using a different port.
  address: localhost
  
  # The name of the database. Has to be created already.
  database: database

  # Credentials for the database.
  username: ""
  password: ""

  # Name of the table to use. Doubles as collection name for MongoDB databases.
  # Works fine if you leave this as default.
  table-name: npcdata

  # Amount of time in seconds before the plugin assumes that the database is offline.
  connection-timeout: 10

  # Can just leave this as it is. Dont change this unless you know what your doing.
  useSSL: false
  
  # MongoDB ClientConnectionURI for use with replica sets and custom connection options
  # - See https://docs.mongodb.com/manual/reference/connection-string/
  # Only change this if you know what your doing and want increased customisation.
  mongodb-connection-string: ''
