author: ${author}
version: ${version}
main: io.github.scroojalix.npcmanager.NPCMain
name: ${project.name}
description: ${description}
depend: [ ProtocolLib ]
api-version: 1.13
permission-message: &noperms "\u00A7cYou do not have permission to use this command."

commands:
  npc:
    aliases: [npcmanager]
    permission: npcmanager.commands.npc
    permission-message: *noperms
    description: NPC commands
    usage: "\u00A7cUnknown argument."
    
permissions:
  npcmanager.*:
    default: op
    description: Implies all NPCManager permissions
    children:
      npcmanager.commands.*: true
  npcmanager.commands.*:
    default: false
    description: Allows use of all NPCManager commands
    children:
      npcmanager.commands.npc: true
  npcmanager.commands.npc:
    default: false
    description: Allows use of NPCManager npc command